### ISSUE TITLE
Feature Request for Podping url history endpoint.

### ISSUE THREAD

**Issue by brianoflondon** [imwatsi/haf-plug-play#19]
I've looked at the code and this is just a bit beyond what I can do, wondering if you can put this on your to do list.

At some point if I could get a dev env set up with access to the back end data (perhaps via a remote SQL call? I might be able to do this kind of stuff or find others to do it.

```
curl -X 'GET' \
  'https://plug-play.imwatsi.com/api/podping/history/latest/url?url=https%3A%2F%2Fsovereignfeeds.com%2Frss%2FSF%2Ffeed.xml&limit=5' \
  -H 'accept: application/json'
  ```
Basically I'd like to expand some of the info in the return to add at the top level.

1. Change `URL` in the input to be `iri`. Throughout Podping we're switching to the terminology of `iri` and `iris` - IRI (International Resource Identifier) is more flexible. 

2. Add fields at the top level of the response:
```
iri
time_since_last_update
```
I think the time should be in seconds and it might be really easy to add this time to each item as well (not essential).

3. More details about each item
If you look at this IRI: `https://sovereignfeeds.com/rss/SF/feed.xml` you can find a few different uses of the different `id` fields and within the custom json `reason` codes. It would be fantsatic if `id`, `reason`, and `medium` could be surfaced for each item in the api return.

As an example look at this trx: `https://hive.ausbit.dev/tx/331e8e7875159750986dfd8ee50c6865c8cf8957`

Current output:  
```
{
  "feed_updates": [
    {
      "trx_id": "aecb22dc98a45e7e3c41c49e601ee4cdb87a5e55",
      "block_num": 64801408,
      "created": "2022-05-29T15:12:06"
    },
    {
      "trx_id": "a92e3fa7328d6e262bda08586099d4adcf437a1e",
      "block_num": 64741898,
      "created": "2022-05-27T13:31:09"
    },
    {
      "trx_id": "9e8a4ce12a43b8a423b323a970738129ded79ec5",
      "block_num": 64741816,
      "created": "2022-05-27T13:27:03"
    },
    {
      "trx_id": "05710e1a2a1de6c6296098e9df07788558b8684b",
      "block_num": 64741735,
      "created": "2022-05-27T13:23:00"
    },
    {
      "trx_id": "aa2227fdc1b4c0f9de321d2a08aa0dd78167eec4",
      "block_num": 62370938,
      "created": "2022-03-06T00:11:57"
    }
  ]
}
```

**Comment by imwatsi** [comment]
Thanks @brianoflondon , added to the list

**Comment by imwatsi** [comment]
Done
